spring:
  thymeleaf:
      cache:false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG
