spring:
  thymeleaf:
      cache:false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 998424060429-3uo96216oc7u46bk4bbnnp7c5q99e1g5.apps.googleusercontent.com
            client-secret: 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
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG